export interface GlossaryTerm {
  fa: string;
  en: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { fa: 'سکون رحم', en: 'Uterine quiescence' },
  { fa: 'رسیدگی سرویکس', en: 'Cervical ripening' },
  { fa: 'نرم‌شدگی سرویکس', en: 'Cervical softening' },
  { fa: 'افاسمان', en: 'Cervical effacement' },
  { fa: 'دیلاتاسیون', en: 'Dilation' },
  { fa: 'فوربگ', en: 'Forebag' },
  { fa: 'انقباضات براکستون-هیکس', en: 'Braxton Hicks contractions' },
  { fa: 'سبک‌شدگی', en: 'Lightening' },
  { fa: 'علامت هگار', en: "Hegar sign" },
  { fa: 'هیالورونان', en: 'Hyaluronan' },
  { fa: 'ریلاکسین', en: 'Relaxin' },
  { fa: 'اتصال شکاف‌دار', en: 'Gap junction' },
  { fa: 'کانکسین-۴۳', en: 'Connexin-43' },
  { fa: 'پروستاگلاندین دهیدروژناز', en: 'PGDH' },
  { fa: 'رفلکس فرگوسن', en: 'Ferguson reflex' },
  { fa: 'حلقه‌ی باندل', en: "Bandl's ring" },
  { fa: 'مکانیسم شولتز', en: 'Schultze mechanism' },
  { fa: 'مکانیسم دانکن', en: 'Duncan mechanism' },
  { fa: 'هماتوم رتروپلاسنتال', en: 'Retroplacental hematoma' },
  { fa: 'میفه‌پریستون', en: 'Mifepristone (RU-486)' },
  { fa: 'یوتروتونین', en: 'Uterotonin' },
  { fa: 'پروتئین مرتبط با انقباض', en: 'Contraction-associated protein (CAP)' },
  { fa: 'قرار جنین (طولی/عرضی)', en: 'Fetal lie' },
  { fa: 'نمایش جنین', en: 'Fetal presentation' },
  { fa: 'حالت جنین', en: 'Fetal attitude / habitus' },
  { fa: 'وضعیت جنین', en: 'Fetal position' },
  { fa: 'مانورهای لئوپولد', en: 'Leopold maneuvers' },
  { fa: 'حرکات اصلی لیبر', en: 'Cardinal movements of labor' },
  { fa: 'آنگاژمان', en: 'Engagement' },
  { fa: 'آسنکلیتیسم', en: 'Asynclitism' },
  { fa: 'عدم‌تناسب سری-لگنی', en: 'Cephalopelvic disproportion (CPD)' },
  { fa: 'دیستوشی', en: 'Dystocia' },
  { fa: 'کاپوت سوکسدانئوم', en: 'Caput succedaneum' },
  { fa: 'مولدینگ', en: 'Molding' },
  { fa: 'تست نیترازین / فرنینگ', en: 'Nitrazine test / Ferning' },
  { fa: 'واحد مونته‌ویدئو', en: 'Montevideo unit' },
  { fa: 'اکسی‌پوت خلفی پایدار', en: 'Persistent occiput posterior' },
  { fa: 'ایستگاه جنین', en: 'Fetal station' },
  { fa: 'نمره‌ی بیشاپ', en: 'Bishop score' },
  { fa: 'مدیریت فعال لیبر', en: 'Active management of labor' },
  { fa: 'کنژوگه‌ی دیاگونال/آبستتریک', en: 'Diagonal / obstetric conjugate' },
  { fa: 'اختلال هیپوتونیک/هیپرتونیک رحم', en: 'Hypotonic / hypertonic uterine dysfunction' },
  { fa: 'لیبر تسریع‌شده', en: 'Precipitous labor' },
  { fa: 'نمایش صورت (منتوم)', en: 'Face presentation (mentum)' },
  { fa: 'نمایش پیشانی', en: 'Brow presentation' },
  { fa: 'قرار عرضی مهمال‌شده', en: 'Neglected transverse lie' },
  { fa: 'پرولاپس بندناف', en: 'Umbilical cord prolapse' },
  { fa: 'نمایش مرکب', en: 'Compound presentation' },
  { fa: 'نمایش فونیک', en: 'Funic presentation' },
  { fa: 'چرخش سفالیک خارجی', en: 'External cephalic version (ECV)' },
  { fa: 'تغییرپذیری ضربه‌به‌ضربه', en: 'Beat-to-beat variability' },
  { fa: 'تسریع', en: 'Acceleration' },
  { fa: 'افت زودرس/دیررس/متغیر', en: 'Early / late / variable deceleration' },
  { fa: 'الگوی سینوزوئیدی', en: 'Sinusoidal pattern' },
  { fa: 'الگوی جهشی', en: 'Saltatory pattern' },
  { fa: 'تاکی‌سیستول', en: 'Tachysystole' },
  { fa: 'آمنیوانفوزیون', en: 'Amnioinfusion' },
  { fa: 'تحریک ویبروآکوستیک', en: 'Vibroacoustic stimulation' },
  { fa: 'پالس اکسی‌متری جنین', en: 'Fetal pulse oximetry' },
  { fa: 'طبقه‌بندی سه‌گروهی NICHD', en: 'NICHD 3-tier category system' },
  { fa: 'تحلیل قطعه‌ی ST جنین', en: 'Fetal ST-segment analysis (STAN)' },
  { fa: 'سندرم آسپیراسیون مکونیوم', en: 'Meconium aspiration syndrome' },
  { fa: 'خودهمبستگی', en: 'Autocorrelation' },
  { fa: 'دیستوشی شانه', en: 'Shoulder dystocia' },
  { fa: 'نشانه‌ی لاک‌پشت', en: 'Turtle sign' },
  { fa: 'مانور مک‌رابرتز', en: 'McRoberts maneuver' },
  { fa: 'مانور روبین', en: 'Rubin maneuver' },
  { fa: 'مانور وودز (کورک‌اسکرو)', en: 'Woods corkscrew maneuver' },
  { fa: 'مانور زاوانلی', en: 'Zavanelli maneuver' },
  { fa: 'سمفیزیوتومی', en: 'Symphysiotomy' },
  { fa: 'کلیدوتومی', en: 'Cleidotomy' },
  { fa: 'ختنه‌ی زنان', en: 'Female genital mutilation (FGM)' },
  { fa: 'دفیبولاسیون', en: 'Defibulation' },
  { fa: 'آسیب اسفنکتر مقعد زایمانی', en: 'OASIS' },
  { fa: 'اپیزیاتومی خط‌میانی/مدیولترال', en: 'Midline / mediolateral episiotomy' },
  { fa: 'کراونینگ', en: 'Crowning' },
  { fa: 'وارونگی رحم', en: 'Uterine inversion' },
  { fa: 'اداره‌ی فعال مرحله‌ی سوم', en: 'Active management of third stage' },
  { fa: 'خروج دستی جفت', en: 'Manual removal of placenta' },
  { fa: 'اسید ترانگزامیک', en: 'Tranexamic acid (TXA)' },
];
