export interface GlossaryTerm {
  fa: string;
  en: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { fa: 'برنامه احیای نوزاد', en: 'Neonatal Resuscitation Program (NRP)' },
  { fa: 'تهویه با فشار مثبت', en: 'Positive-pressure ventilation (PPV)' },
  { fa: 'فشار مثبت پیوسته راه هوایی', en: 'Continuous positive airway pressure (CPAP)' },
  { fa: 'شنت راست‌به‌چپ', en: 'Right-to-left shunt' },
  { fa: 'سوراخ بیضی', en: 'Foramen ovale' },
  { fa: 'مجرای شریانی', en: 'Ductus arteriosus' },
  { fa: 'آپنه', en: 'Apnea' },
  { fa: 'برادی‌کاردی', en: 'Bradycardia' },
  { fa: 'تاکی‌کاردی', en: 'Tachycardia' },
  { fa: 'سیانوز', en: 'Cyanosis' },
  { fa: 'ارتباط حلقه‌بسته', en: 'Closed-loop communication' },
  { fa: 'آگاهی از موقعیت', en: 'Situational awareness' },
  { fa: 'بهبود کیفیت', en: 'Quality improvement (QI)' },
  { fa: 'نشست پیش از احیا', en: 'Briefing' },
  { fa: 'جمع‌بندی پس از احیا', en: 'Debriefing' },
  { fa: 'آگاهی بر موقعیت', en: 'Situational awareness' },
  { fa: 'کاتتر سیاهرگ نافی', en: 'Umbilical venous catheter (UVC)' },
  { fa: 'دیستوشی شانه', en: 'Shoulder dystocia' },
  { fa: 'کوریوآمنیونیت', en: 'Chorioamnionitis' },
  { fa: 'گیره زدن تأخیری بند ناف', en: 'Delayed cord clamping' },
  { fa: 'تنفس منقطع', en: 'Gasping' },
  { fa: 'آکروسیانوز', en: 'Acrocyanosis' },
  { fa: 'سیانوز مرکزی', en: 'Central cyanosis' },
  { fa: 'پالس‌اکسی‌متری', en: 'Pulse oximetry' },
  { fa: 'جریان آزاد اکسیژن', en: 'Free-flow oxygen' },
  { fa: 'فشار مثبت پیوسته‌ی راه هوایی', en: 'Continuous positive airway pressure (CPAP)' },
  { fa: 'مایع آمنیونی مکونیومی', en: 'Meconium-stained amniotic fluid' },
  { fa: 'فعالیت الکتریکی بدون نبض', en: 'Pulseless electrical activity (PEA)' },
  { fa: 'بگ خودگشا', en: 'Self-inflating bag' },
  { fa: 'بگ وابسته به جریان', en: 'Flow-inflating bag' },
  { fa: 'تی‌پیس احیا', en: 'T-piece resuscitator' },
  { fa: 'بیشینه فشار دمی', en: 'Peak inspiratory pressure (PIP)' },
  { fa: 'فشار مثبت پایان بازدمی', en: 'Positive end-expiratory pressure (PEEP)' },
  { fa: 'ماسک حنجره‌ای', en: 'Laryngeal mask airway (LMA)' },
  { fa: 'لوله دهانی معدی', en: 'Orogastric tube' },
  { fa: 'گام‌های اصلاحی تهویه', en: 'Ventilation corrective steps (MR. SOPA)' },
  { fa: 'آشکارساز دی‌اکسیدکربن', en: 'CO2 detector / capnograph' },
  { fa: 'لارنگوسکوپ', en: 'Laryngoscope' },
  { fa: 'والکولا', en: 'Vallecula' },
  { fa: 'اپی‌گلوت', en: 'Epiglottis' },
  { fa: 'گلوت', en: 'Glottis' },
  { fa: 'کارینا', en: 'Carina' },
  { fa: 'فاصله بینی تا تراگوس', en: 'Nasal-tragus length (NTL)' },
  { fa: 'مکنده مکونیوم', en: 'Meconium aspirator' },
  { fa: 'ویدئولارنگوسکوپ', en: 'Video laryngoscope' },
  { fa: 'فشردن قفسه سینه', en: 'Chest compressions' },
  { fa: 'روش دو‌شست', en: 'Two-thumb technique' },
  { fa: 'زائده جناغی', en: 'Xiphoid process' },
  { fa: 'اپی‌نفرین', en: 'Epinephrine' },
  { fa: 'حجم‌افزا', en: 'Volume expander' },
  { fa: 'شوک هیپوولمیک', en: 'Hypovolemic shock' },
  { fa: 'سوزن درون‌استخوانی', en: 'Intraosseous (IO) needle' },
  { fa: 'خار درشت‌نی', en: 'Tibial tuberosity' },
  { fa: 'ژله وارتون', en: "Wharton's jelly" },
  { fa: 'هیپوترمی', en: 'Hypothermia' },
  { fa: 'کمپلیانس ریه', en: 'Lung compliance' },
  { fa: 'سورفاکتانت', en: 'Surfactant' },
  { fa: 'تجویز کمتر تهاجمی سورفاکتانت', en: 'Less Invasive Surfactant Administration (LISA)' },
  { fa: 'لوله‌گذاری-سورفاکتانت-خروج لوله', en: 'Intubate-Surfactant-Extubate (INSURE)' },
  { fa: 'وضعیت ترندلنبرگ', en: 'Trendelenburg position' },
  { fa: 'گرم‌کننده‌ی خودتنظیم‌شونده', en: 'Servo-controlled warmer' },
  { fa: 'دوشیدن بند ناف', en: 'Umbilical cord milking' },
  { fa: 'خونریزی درون‌بطنی', en: 'Intraventricular hemorrhage (IVH)' },
  { fa: 'پرفشاری پایدار خون ریوی نوزادی', en: 'Persistent pulmonary hypertension of the newborn (PPHN)' },
  { fa: 'آنسفالوپاتی هیپوکسیک-ایسکمیک', en: 'Hypoxic-ischemic encephalopathy (HIE)' },
  { fa: 'سرمادرمانی', en: 'Therapeutic hypothermia' },
  { fa: 'نکروز توبولی حاد', en: 'Acute tubular necrosis (ATN)' },
  { fa: 'اکسیژن‌رسانی غشای خارج بدنی', en: 'Extracorporeal membrane oxygenation (ECMO)' },
  { fa: 'بی‌کربنات سدیم', en: 'Sodium bicarbonate' },
  { fa: 'پنوموتوراکس', en: 'Pneumothorax' },
  { fa: 'افوزیون پلور', en: 'Pleural effusion' },
  { fa: 'ترانس‌ایلومیناسیون', en: 'Transillumination' },
  { fa: 'توراسنتز', en: 'Thoracentesis' },
  { fa: 'توالی رابین', en: 'Robin sequence' },
  { fa: 'آترزی کوآن', en: 'Choanal atresia' },
  { fa: 'فتق دیافراگمی بدو تولد', en: 'Congenital diaphragmatic hernia (CDH)' },
  { fa: 'هیپوپلازی ریوی', en: 'Pulmonary hypoplasia' },
  { fa: 'نالوکسان', en: 'Naloxone' },
  { fa: 'میلومننگوسل', en: 'Myelomeningocele' },
  { fa: 'گاستروشزی', en: 'Gastroschisis' },
  { fa: 'امفالوسل', en: 'Omphalocele' },
  { fa: 'خودمختاری', en: 'Autonomy' },
  { fa: 'خیررسانی', en: 'Beneficence' },
  { fa: 'ضرر نرساندن', en: 'Nonmaleficence' },
  { fa: 'عدالت', en: 'Justice' },
  { fa: 'رضایت آگاهانه', en: 'Informed consent' },
  { fa: 'مراقبت تسکینی', en: 'Palliative care' },
  { fa: 'فناوری کمک‌باروری', en: 'Assisted reproductive technology (ART)' },
  { fa: 'ارگونومی', en: 'Ergonomics' },
  { fa: 'عوامل انسانی', en: 'Human factors' },
  { fa: 'طرح احیا', en: 'Resuscitation plan' },
  { fa: 'بار شناختی', en: 'Cognitive load' },
  { fa: 'کالپس ناگهانی و پیش‌بینی‌نشده پس از تولد', en: 'Sudden unexpected postnatal collapse (SUPC)' },
  { fa: 'مراقبت پیشرفته کودکان', en: 'Pediatric Advanced Life Support (PALS)' },
  { fa: 'دیسپلازی برونکوپولمونر', en: 'Bronchopulmonary dysplasia (BPD)' },
  { fa: 'کاتتر مرکزی از راه وریدهای محیطی', en: 'Peripherally inserted central catheter (PICC)' },
];
