import { ChapterData } from '@studyhub/shared-models';

export const chapter: ChapterData = {
  id: "ch06-surgical",
  order: 5,
  code: "ch06",
  titleFa: "موارد نیازمند جراحی",
  titleEn: "Surgical Conditions",
  summaryFa: "بانک سؤال تعاملی فصل موارد نیازمند جراحی نوزاد: ناهنجاری‌های مادرزادی جراحی و اداره‌ی اولیه‌ی آن‌ها — بر پایه‌ی برنامه‌ی ACoRN.",
  readingMinutes: 74,
  sections: [
    {
      heading: "درباره‌ی این فصل",
      paragraphsHtml: ["<p>این فصل صرفاً شامل یک بانک سؤال تعاملی (چهارگزینه‌ای، کوتاه‌پاسخ، و صحیح/غلط) است که از کتاب «مراقبت بحرانی نوزاد در معرض خطر» (برنامه‌ی آموزشی ACoRN) اقتباس شده؛ بدون متن درسی جداگانه، مستقیماً به بانک سؤال زیر مراجعه کنید.</p>"],
    },
  ],
  quiz: [
    {
      id: "mcq1",
      type: 'mcq',
      question: "کدام حالت جراحی نیازمند جراحی فوری (emergency) است؟",
      choices: ["تنگی دریچهٔ پیلوری", "فتق مادرزادی دیافراگمی", "نقص دیواره قدامی شکم", "تنهای کلوآکال"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: فتق مادرزادی دیافراگمی",
    },
    {
      id: "mcq2",
      type: 'mcq',
      question: "فتق مادرزادی دیافراگمی در کدام سطح رخ می‌دهد؟",
      choices: ["پشتی", "قدامی", "جانبی (بیشتر اوقات)", "کل دیافراگم"],
      correctIndex: 2,
      explanation: "پاسخ صحیح: جانبی (بیشتر اوقات)",
    },
    {
      id: "mcq3",
      type: 'mcq',
      question: "در نوزاد با فتق مادرزادی دیافراگمی، کدام عضو در قفسه سینه قرار می‌گیرد؟",
      choices: ["کبد", "کلیه", "معده و روده", "طحال"],
      correctIndex: 2,
      explanation: "پاسخ صحیح: معده و روده",
    },
    {
      id: "mcq4",
      type: 'mcq',
      question: "علائم فتق مادرزادی دیافراگمی کدام است؟",
      choices: ["بیماری بدون علائم", "دیسترس تنفسی شدید و سیانوز", "فقط بیماری", "فقط عدم اشتهایی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: دیسترس تنفسی شدید و سیانوز",
    },
    {
      id: "mcq5",
      type: 'mcq',
      question: "درمان اولیه برای نوزاد با فتق مادرزادی دیافراگمی چیست؟",
      choices: ["تهویه با بگ و ماسک فوری", "درمان حمایتی و جراحی؛ بدون تهویه با بگ و ماسک", "کاهش دما", "فقط مراقبت"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: درمان حمایتی و جراحی؛ بدون تهویه با بگ و ماسک",
    },
    {
      id: "mcq6",
      type: 'mcq',
      question: "نقص دیواره قدامی شکم (gastroschisis) چیست؟",
      choices: ["صرف فتق ساده", "نقص ۲-۱۰ سانتی‌متری در نزدیکی ناف", "فتق چپ طرف", "بیماری پوستی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: نقص ۲-۱۰ سانتی‌متری در نزدیکی ناف",
    },
    {
      id: "mcq7",
      type: 'mcq',
      question: "در gastroschisis، کدام اندام معمولاً برآمده است؟",
      choices: ["کبد", "روده و کبد", "صرف روده اغلب", "تنها معده"],
      correctIndex: 2,
      explanation: "پاسخ صحیح: صرف روده اغلب",
    },
    {
      id: "mcq8",
      type: 'mcq',
      question: "تفاوت میان gastroschisis و نقص ومفالوسل چیست؟",
      choices: ["هیچ تفاوتی ندارند", "gastroschisis دور ناف نیست و معمولاً راست طرف است", "تنهای نام مختلف", "اولی شدید‌تر است"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: gastroschisis دور ناف نیست و معمولاً راست طرف است",
    },
    {
      id: "mcq9",
      type: 'mcq',
      question: "درمان اولیه gastroschisis چیست؟",
      choices: ["جراحی فوری برای بستن دیواره", "پوشش معقیم، حفاظت دما، تهویه و جراحی فوری یا تدریجی", "فقط مراقبت"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: پوشش معقیم، حفاظت دما، تهویه و جراحی فوری یا تدریجی",
    },
    {
      id: "mcq10",
      type: 'mcq',
      question: "نقص ومفالوسل کدام نقص است؟",
      choices: ["نقص دیافراگم", "نقص دیواره شکم در سایت ناف", "نقص فقط پوستی", "فتق ساده"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: نقص دیواره شکم در سایت ناف",
    },
    {
      id: "mcq11",
      type: 'mcq',
      question: "در نقص ومفالوسل، کدام اندام در کیسهٔ برآمده قرار دارد؟",
      choices: ["تنها معده", "روده و معمولاً کبد", "تنها کلیه", "صرف چربی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: روده و معمولاً کبد",
    },
    {
      id: "mcq12",
      type: 'mcq',
      question: "درمان نقص ومفالوسل شامل چیست؟",
      choices: ["فوری جراحی", "پوشش معقیم، حفاظت، تهویه و جراحی در موقع مناسب", "بدون درمان جراحی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: پوشش معقیم، حفاظت، تهویه و جراحی در موقع مناسب",
    },
    {
      id: "mcq13",
      type: 'mcq',
      question: "تنگی دریچهٔ پیلوری (pyloric stenosis) در چه سنی رخ می‌دهد؟",
      choices: ["بلافاصله پس از تولد", "۲-۸ هفته پس از تولد", "بعد از ۳ ماه", "بعد از ۶ ماه"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: ۲-۸ هفته پس از تولد",
    },
    {
      id: "mcq14",
      type: 'mcq',
      question: "علائم تنگی دریچهٔ پیلوری کدام است؟",
      choices: ["اسهال", "استفراغ متکرر و پروژکتیل، وزن کم یا کاهش وزن", "تب و بیماری", "فقط آپنه"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: استفراغ متکرر و پروژکتیل، وزن کم یا کاهش وزن",
    },
    {
      id: "mcq15",
      type: 'mcq',
      question: "درمان تنگی دریچهٔ پیلوری چیست؟",
      choices: ["دارو درمانی", "جراحی (pyloromyotomy)", "فقط تغذیه خاص", "بدون درمان"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: جراحی (pyloromyotomy)",
    },
    {
      id: "mcq16",
      type: 'mcq',
      question: "استرازیا یا اتریزیا (atresia) در دستگاه گوارش چیست؟",
      choices: ["تنگی", "عدم وجود یا بند شدن کامل راه‌رو", "فتق", "التهاب"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: عدم وجود یا بند شدن کامل راه‌رو",
    },
    {
      id: "mcq17",
      type: 'mcq',
      question: "اتریزیای مرئی (esophageal atresia) با چه کیفیتی همراه است؟",
      choices: ["فقط تنگی", "معمولاً با فیستولای تراشه‌ای (TEF)", "صرف بیماری", "بدون علائم"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: معمولاً با فیستولای تراشه‌ای (TEF)",
    },
    {
      id: "mcq18",
      type: 'mcq',
      question: "علائم اتریزیای مرئی چیست؟",
      choices: ["بیماری تنها", "بیماری، سالیوهٔ بیشتر و دیسترس تنفسی", "فقط سالیوهٔ بیشتر", "بدون علائم"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: بیماری، سالیوهٔ بیشتر و دیسترس تنفسی",
    },
    {
      id: "mcq19",
      type: 'mcq',
      question: "درمان اتریزیای مرئی چیست؟",
      choices: ["دارو درمانی", "لوله دهانی‑معدی و جراحی ترمیم", "تغذیه عادی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: لوله دهانی‑معدی و جراحی ترمیم",
    },
    {
      id: "mcq20",
      type: 'mcq',
      question: "اتریزیای دوئدنم در کدام درجه رخ می‌دهد؟",
      choices: ["معمولاً", "معمولاً درجهٔ دوم", "درجهٔ سوم", "درجهٔ چهارم"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: معمولاً درجهٔ دوم",
    },
    {
      id: "mcq21",
      type: 'mcq',
      question: "علائم اتریزیای دوئدنم کدام است؟",
      choices: ["اسهال", "استفراغ و بیماری (bile-stained)، شکم متورم", "تب", "فقط آپنه"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: استفراغ و بیماری (bile-stained)، شکم متورم",
    },
    {
      id: "mcq22",
      type: 'mcq',
      question: "درمان اتریزیای دوئدنم چیست؟",
      choices: ["درمان حمایتی فقط", "لوله دهانی‑معدی و جراحی", "دارو درمانی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: لوله دهانی‑معدی و جراحی",
    },
    {
      id: "mcq23",
      type: 'mcq',
      question: "آئوسوفاژیس (ileitis) یا آنتریتیس در نوزادی چیست؟",
      choices: ["تنگی", "التهاب روده", "فتق", "اتریزیا"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: التهاب روده",
    },
    {
      id: "mcq24",
      type: 'mcq',
      question: "نکروز آنتریتیس نکروتیزینگ (NEC) در چه نوزادانی شایع است؟",
      choices: ["ترم سالم", "نارس و نوزادان بیمار", "نوزادان سالم", "فقط معیوب مادرزادی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: نارس و نوزادان بیمار",
    },
    {
      id: "mcq25",
      type: 'mcq',
      question: "علائم NEC کدام است؟",
      choices: ["فقط استفراغ", "شکم متورم، خون در مدفوع، ناپایدار قلبی‑تنفسی", "فقط بیماری", "فقط اسهال"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: شکم متورم، خون در مدفوع، ناپایدار قلبی‑تنفسی",
    },
    {
      id: "mcq26",
      type: 'mcq',
      question: "درمان NEC شامل چیست؟",
      choices: ["درمان حمایتی فقط", "درمان حمایتی، ضد میکروب و جراحی در صورت نیاز", "جراحی فوری"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: درمان حمایتی، ضد میکروب و جراحی در صورت نیاز",
    },
    {
      id: "mcq27",
      type: 'mcq',
      question: "سپاسچه (meconium ileus) در نوزادی چیست؟",
      choices: ["انسداد معمولی", "انسداد ناشی از مکونیوم ترشح‌شدهٔ و غلیظ", "فتق", "اتریزیا"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: انسداد ناشی از مکونیوم ترشح‌شدهٔ و غلیظ",
    },
    {
      id: "mcq28",
      type: 'mcq',
      question: "سپاسچه مکونیوم معمولاً با چه بیماری مادرزادی همراه است؟",
      choices: ["فقط معیوبی قلبی", "تب کیستیک و کم‌کاری پانکراس", "صرف صرع", "تنهای خودعفونتی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: تب کیستیک و کم‌کاری پانکراس",
    },
    {
      id: "mcq29",
      type: 'mcq',
      question: "علائم مکونیوم سپاسچه کدام است؟",
      choices: ["فقط بیماری", "شکم متورم، استفراغ و بیماری، عدم مدفوع", "فقط اسهال", "بدون علائم"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: شکم متورم، استفراغ و بیماری، عدم مدفوع",
    },
    {
      id: "mcq30",
      type: 'mcq',
      question: "درمان اولیه مکونیوم سپاسچه چیست؟",
      choices: ["جراحی فوری", "درمان حمایتی و اگر لازم جراحی", "دارو درمانی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: درمان حمایتی و اگر لازم جراحی",
    },
    {
      id: "mcq31",
      type: 'mcq',
      question: "انسداد روده (bowel obstruction) عارضات ناشی از چیست؟",
      choices: ["صرف ترومای تولد", "اتریزیا، سپاسچه، volvolus، invagination و فتق", "فقط نارسی", "صرف عفونت"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: اتریزیا، سپاسچه، volvolus، invagination و فتق",
    },
    {
      id: "mcq32",
      type: 'mcq',
      question: "volvolus (پیچش روده) علائم آن چیست؟",
      choices: ["فقط بیماری", "شکم متورم، استفراغ و بیماری، درد شکم", "فقط اسهال", "بدون علائم"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: شکم متورم، استفراغ و بیماری، درد شکم",
    },
    {
      id: "mcq33",
      type: 'mcq',
      question: "invagination (کشش روده) بیشتر در کدام سن رخ می‌دهد؟",
      choices: ["بلافاصله پس از تولد", "۶ تا ۱۸ ماه", "۳ تا ۶ سال", "بزرگسالی"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: ۶ تا ۱۸ ماه",
    },
    {
      id: "mcq34",
      type: 'mcq',
      question: "فتق رانی (inguinal hernia) در نوزادان چه فرکانسی دارد؟",
      choices: ["خیلی نادر", "شایع (۳۰۰۰ تا ۵۰۰۰ نوزاد از هر مراقبت)", "فقط پسران", "فقط دختران"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: شایع (۳۰۰۰ تا ۵۰۰۰ نوزاد از هر مراقبت)",
    },
    {
      id: "mcq35",
      type: 'mcq',
      question: "درمان فتق رانی در نوزادان چیست؟",
      choices: ["درمان حمایتی فقط", "جراحی اگر incarcerated یا symptomatic", "بدون درمان"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: جراحی اگر incarcerated یا symptomatic",
    },
    {
      id: "mcq36",
      type: 'mcq',
      question: "ارتوسل (hydrocele) در نوزادان چیست؟",
      choices: ["فتق", "جمع شدن مایع در کیسهٔ مخصی", "التهاب", "اتریزیا"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: جمع شدن مایع در کیسهٔ مخصی",
    },
    {
      id: "mcq37",
      type: 'mcq',
      question: "اکثر ارتوسل نوزادی چه شود؟",
      choices: ["دائمی است", "خود به خود درجهٔ ۱۲-۱۸ ماه حل می‌شود", "نیاز به جراحی دارد", "خطرناک است"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: خود به خود درجهٔ ۱۲-۱۸ ماه حل می‌شود",
    },
    {
      id: "mcq38",
      type: 'mcq',
      question: "کریپتورکیدیسم (عدم فرود بیضهٔ) در نوزادی چیست؟",
      choices: ["بیماری معمولی", "عدم فرود بیضه به کیسهٔ مخصی", "فتق", "التهاب"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: عدم فرود بیضه به کیسهٔ مخصی",
    },
    {
      id: "mcq39",
      type: 'mcq',
      question: "درمان کریپتورکیدیسم در نوزادی چیست؟",
      choices: ["درمان دارویی فقط", "درمان هورمونی یا جراحی اگر تا ۱ سال حل نشود", "بدون درمان"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: درمان هورمونی یا جراحی اگر تا ۱ سال حل نشود",
    },
    {
      id: "mcq40",
      type: 'mcq',
      question: "مالروتیشن (نامنظمی چرخش روده) چه خطری دارد؟",
      choices: ["خطر کم", "خطر volvolus و نکروز روده", "صرف بیماری", "بدون خطر"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: خطر volvolus و نکروز روده",
    },
    {
      id: "mcq41",
      type: 'mcq',
      question: "تشخیص مالروتیشن چگونه است؟",
      choices: ["فقط بالینی", "تصویرگری (عکس شکم، اسکن)", "فقط معاینهٔ فیزیکی", "ندارد"],
      correctIndex: 1,
      explanation: "پاسخ صحیح: تصویرگری (عکس شکم، اسکن)",
    },
    {
      id: "short1",
      type: 'short',
      prompt: "فتق مادرزادی دیافراگمی چیست و علل آن کدام است؟",
      answer: "نقص در دیافراگم (معمولاً جانبی) که باعث برآمدن اندام‌های شکمی به قفسه سینه می‌شود؛ دلیل نامشخص (ناهنجاری رشدی).",
    },
    {
      id: "short2",
      type: 'short',
      prompt: "علائم فتق مادرزادی دیافراگمی در نوزاد چیست؟",
      answer: "دیسترس تنفسی فوری، سیانوز، خساستینگ دیر در تنفس، شکم نرم یا کشیده‌شدهٔ (از فقدان اندام).",
    },
    {
      id: "short3",
      type: 'short',
      prompt: "درمان اولیه برای نوزاد با فتق مادرزادی دیافراگمی چیست و چرا بگ و ماسک ممنوع است؟",
      answer: "تهویه مکانیکی فوری، لوله تراشه و لوله دهانی‑معدی برای کاهش فشار گاز شکمی؛ بگ و ماسک ممنوع است زیرا گاز بیشتری به معده و روده می‌رود و وضعیت بدتر می‌شود.",
    },
    {
      id: "short4",
      type: 'short',
      prompt: "gastroschisis چیست و علائم آن کدام است؟",
      answer: "نقص دیواره شکم ۲-۱۰ سانتی‌متری که معمولاً راست طرف ناف است و روده، کبد، و دیگر اندام‌ها برآمده هستند؛ علائم: شکم متورم، روده برآمده و مردهٔ بدون پوشش.",
    },
    {
      id: "short5",
      type: 'short',
      prompt: "تفاوت gastroschisis و نقص ومفالوسل در محل نقص و محتویات چیست؟",
      answer: "gastroschisis: دور ناف نیست (اغلب راست طرف)، روده و کبد برآمده، کیسهٔ نیست؛ ومفالوسل: در سایت ناف، روده معمولاً و کبد اغلب در کیسهٔ transparent برآمده.",
    },
    {
      id: "short6",
      type: 'short',
      prompt: "درمان gastroschisis چیست و پیش‌آیند آن چگونه است؟",
      answer: "درمان اولیه: پوشش معقیم، حفاظت دما، IV fluids و تهویه; جراحی: بستن دیواره در مراحل یا فوری; پیش‌آیند: بهتر از ومفالوسل، اکثریت نجات می‌یابند اما معیوبی‌های عصبی یا سوء جذب ممکن است.",
    },
    {
      id: "short7",
      type: 'short',
      prompt: "تنگی دریچهٔ پیلوری (pyloric stenosis) چیست و در چه سنی رخ می‌دهد؟",
      answer: "تضخیم عضلهٔ pylorus که انسداد خروج معده ایجاد می‌کند؛ رخ می‌دهد در ۲-۸ هفته پس از تولد، بیشتر در پسران.",
    },
    {
      id: "short8",
      type: 'short',
      prompt: "علائم تنگی دریچهٔ پیلوری کدام است؟",
      answer: "استفراغ proyektil (متوجه) بلافاصله پس از تغذیه، وزن کم یا کاهش وزن، تغذیه مدام، شکم نرم.",
    },
    {
      id: "short9",
      type: 'short',
      prompt: "درمان تنگی دریچهٔ پیلوری چیست؟",
      answer: "جراحی (pyloromyotomy یا Ramstedt operation) که شامل بریدن عضلهٔ منقبض شده است؛ بدون جراحی، نوزاد ضایع می‌شود.",
    },
    {
      id: "short10",
      type: 'short',
      prompt: "اتریزیای مرئی (esophageal atresia) چیست و با چه بیماری همراه است؟",
      answer: "عدم وجود یا بند شدن کامل راه‌رو مرئی؛ معمولاً با فیستولای تراشه‌ای (TEF) همراه است که اتصال غیرطبیعی مرئی به تراشه ایجاد می‌کند.",
    },
    {
      id: "short11",
      type: 'short',
      prompt: "علائم اتریزیای مرئی کدام است؟",
      answer: "بیماری شدید، سالیوهٔ بیشتر، دیسترس تنفسی (به دلیل آسپیراسیون سالیوه به تراشه)، عدم توانایی برای شیر خوردن.",
    },
    {
      id: "short12",
      type: 'short',
      prompt: "درمان اتریزیای مرئی و TEF چیست؟",
      answer: "لوله دهانی‑معدی برای تخلیهٔ سالیوه، تهویه مکانیکی و جراحی ترمیم شامل بریدن فیستولا و اتصال دوسر مرئی.",
    },
    {
      id: "short13",
      type: 'short',
      prompt: "اتریزیای دوئدنم چیست و علائم آن کدام است؟",
      answer: "عدم وجود یا بند شدن کامل دوئدنم؛ علائم: استفراغ bile-stained در ۲۴-۴۸ ساعت پس از تولد، شکم متورم.",
    },
    {
      id: "short14",
      type: 'short',
      prompt: "درمان اتریزیای دوئدنم چیست؟",
      answer: "جراحی (duodenoduodenostomy) برای ایجاد اتصال bypass؛ درمان حمایتی با تهویه و IV fluids.",
    },
    {
      id: "short15",
      type: 'short',
      prompt: "نکروز آنتریتیس نکروتیزینگ (NEC) چیست و در چه نوزادانی رخ می‌دهد؟",
      answer: "بیماری التهابی روده که باعث نکروز (مرگ بافت) روده می‌شود؛ شایع در نوزادان نارس و بیمار.",
    },
    {
      id: "short16",
      type: 'short',
      prompt: "علائم NEC کدام است؟",
      answer: "شکم متورم و حساس، استفراغ و بیماری، خون در مدفوع (gross یا hidden)، ناپایداری قلبی‑تنفسی، بحران سپسیس.",
    },
    {
      id: "short17",
      type: 'short',
      prompt: "درمان NEC چیست؟",
      answer: "درمان حمایتی (IV nutrition، دارو‌های حمایتی)، antibiotic پهن‌طیفی، NPO (بدون مصرف غذا از دهان)، جراحی اگر perforated یا necrotized بافت وجود دارد.",
    },
    {
      id: "short18",
      type: 'short',
      prompt: "مکونیوم سپاسچه (meconium ileus) چیست و با چه بیماری مرتبط است؟",
      answer: "انسداد روده ناشی از مکونیوم ترشح‌شدهٔ و غلیظ در نوزادی؛ معمولاً با تب کیستیک (CF) مرتبط که کم‌کاری پانکراس ایجاد می‌کند.",
    },
    {
      id: "short19",
      type: 'short',
      prompt: "علائم مکونیوم سپاسچه کدام است؟",
      answer: "شکم متورم در ۲۴-۴۸ ساعت پس از تولد، استفراغ و بیماری، عدم مدفوع یا مدفوع خاکستری رنگ.",
    },
    {
      id: "short20",
      type: 'short',
      prompt: "درمان مکونیوم سپاسچه چیست؟",
      answer: "درمان حمایتی و NG-tube irrigation با acetylcysteine برای حل مکونیوم غلیظ؛ جراحی اگر غیرموثر بود یا اگر enterostomy یا anastomosis لازم بود.",
    },
    {
      id: "short21",
      type: 'short',
      prompt: "volvolus (پیچش روده) چیست و پیش‌آیند آن چگونه است؟",
      answer: "چرخش روده بر روی mesentery خود که خون‌رسانی را مختل می‌کند؛ شامل نکروز روده و مرگ اگر درمان نشود.",
    },
    {
      id: "short22",
      type: 'short',
      prompt: "علائم volvolus کدام است؟",
      answer: "شکم متورم و حساس، درد شدید، استفراغ bile-stained، علائم شوک پس از نکروز.",
    },
    {
      id: "short23",
      type: 'short',
      prompt: "درمان volvolus چیست؟",
      answer: "جراحی فوری برای تصحیح پیچش، بررسی برای نکروز روده و استئومی یا resection اگر بافت مردهٔ باشد.",
    },
    {
      id: "short24",
      type: 'short',
      prompt: "invagination (کشش روده) چیست و بیشتر در کدام سن رخ می‌دهد؟",
      answer: "داخل شدن یک بخش روده به بخش مجاور آن؛ شایع در ۶-۱۸ ماه، بیشتر در پسران و بعد از عفونت ویروسی.",
    },
    {
      id: "short25",
      type: 'short',
      prompt: "علائم invagination کدام است؟",
      answer: "درد شکم دوره‌ای، استفراغ، اسهال (خون دار) و یا مدفوع نیست، توده‌ای احساس شود در شکم.",
    },
    {
      id: "short26",
      type: 'short',
      prompt: "درمان invagination چیست؟",
      answer: "reduction غیرجراحی با hydrostatic یا pneumatic enema (ممکن است سفت باشد) یا جراحی اگر failure یا perforation.",
    },
    {
      id: "short27",
      type: 'short',
      prompt: "فتق رانی (inguinal hernia) در نوزادان چیست و درمان آن چیست؟",
      answer: "برآمدگی بافت (معمولاً روده یا ovary) از طریق نقص در canal کشاقی؛ درمان: جراحی اگر incarcerated (خط خود را ندارد) یا symptomatic.",
    },
    {
      id: "short28",
      type: 'short',
      prompt: "ارتوسل (hydrocele) در نوزادان چیست و پیش‌آیند آن چیست؟",
      answer: "جمع شدن مایع در کیسهٔ مخصی؛ معمولاً ناشی از عدم بسته‌شدن processus vaginalis؛ اکثریت خود به خود در ۱۲-۱۸ ماه حل می‌شود.",
    },
    {
      id: "short29",
      type: 'short',
      prompt: "کریپتورکیدیسم (undescended testis) در نوزادی چیست و درمان آن چیست؟",
      answer: "عدم فرود بیضه از فاصلهٔ ابدومینال به کیسهٔ مخصی؛ درمان: درمان هورمونی یا جراحی اگر تا ۱ سال حل نشود.",
    },
    {
      id: "short30",
      type: 'short',
      prompt: "مالروتیشن (intestinal malrotation) چیست و خطرات آن کدام است؟",
      answer: "نامنظمی در چرخش روده در حین رشد جنینی؛ خطرات: volvolus و نکروز روده ممکن است.",
    },
    {
      id: "tf1",
      type: 'truefalse',
      statement: "فتق مادرزادی دیافراگمی معمولاً سمت راست است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf2",
      type: 'truefalse',
      statement: "در فتق مادرزادی دیافراگمی، تهویه با بگ و ماسک می‌تواند وضعیت خطرناک‌تر کند.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf3",
      type: 'truefalse',
      statement: "gastroschisis نقص دیواره شکم در سایت ناف است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf4",
      type: 'truefalse',
      statement: "gastroschisis بدتر از ومفالوسل است و پیش‌آیند بدتری دارد.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf5",
      type: 'truefalse',
      statement: "نقص ومفالوسل معمولاً محتوای کبد و روده را دارد.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf6",
      type: 'truefalse',
      statement: "تنگی دریچهٔ پیلوری در نوزادان ترم سالم شایع است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf7",
      type: 'truefalse',
      statement: "استفراغ در تنگی دریچهٔ پیلوری معمولاً projectile است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf8",
      type: 'truefalse',
      statement: "تنگی دریچهٔ پیلوری بیشتر در دختران رخ می‌دهد.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf9",
      type: 'truefalse',
      statement: "درمان تنگی دریچهٔ پیلوری فقط دارویی است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf10",
      type: 'truefalse',
      statement: "اتریزیای مرئی معمولاً با فیستولای تراشه‌ای همراه است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf11",
      type: 'truefalse',
      statement: "اتریزیای مرئی علائم دیسترس تنفسی ایجاد می‌کند.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf12",
      type: 'truefalse',
      statement: "درمان اتریزیای مرئی فقط NG-tube است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf13",
      type: 'truefalse',
      statement: "اتریزیای دوئدنم بلافاصله پس از تولد علائم ایجاد می‌کند.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf14",
      type: 'truefalse',
      statement: "استفراغ در اتریزیای دوئدنم معمولاً bile-stained است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf15",
      type: 'truefalse',
      statement: "NEC معمولاً در نوزادان ترم سالم رخ می‌دهد.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf16",
      type: 'truefalse',
      statement: "علائم NEC شامل خون در مدفوع است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf17",
      type: 'truefalse',
      statement: "درمان NEC همیشه جراحی است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf18",
      type: 'truefalse',
      statement: "مکونیوم سپاسچه تنها با تب کیستیک مرتبط نیست.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf19",
      type: 'truefalse',
      statement: "درمان مکونیوم سپاسچه می‌تواند acetylcysteine irrigation را شامل کند.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf20",
      type: 'truefalse',
      statement: "volvolus خطری برای نکروز روده است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf21",
      type: 'truefalse',
      statement: "علائم volvolus شامل bile-stained vomiting است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf22",
      type: 'truefalse',
      statement: "درمان volvolus می‌تواند غیرجراحی باشد.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf23",
      type: 'truefalse',
      statement: "invagination شایع در نوزادان کمتر از ۶ ماه است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf24",
      type: 'truefalse',
      statement: "invagination معمولاً بیشتر در پسران رخ می‌دهد.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf25",
      type: 'truefalse',
      statement: "درمان invagination می‌تواند hydrostatic enema را شامل کند.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf26",
      type: 'truefalse',
      statement: "درمان invagination همیشه جراحی است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf27",
      type: 'truefalse',
      statement: "فتق رانی در نوزادان خیلی شایع است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf28",
      type: 'truefalse',
      statement: "درمان فتق رانی می‌تواند جراحی شامل بسته‌شدن نقص است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf29",
      type: 'truefalse',
      statement: "اکثر ارتوسل نوزادی خود به خود حل می‌شود.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf30",
      type: 'truefalse',
      statement: "کریپتورکیدیسم باید تا ۱ سال جراحی شود.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf31",
      type: 'truefalse',
      statement: "مالروتیشن همیشه علائم ایجاد می‌کند.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf32",
      type: 'truefalse',
      statement: "مالروتیشن خطر volvolus را افزایش می‌دهد.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf33",
      type: 'truefalse',
      statement: "تشخیص مالروتیشن فقط بالینی است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf34",
      type: 'truefalse',
      statement: "gastroschisis معمولاً سمت چپ ناف است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf35",
      type: 'truefalse',
      statement: "درمان فتق مادرزادی دیافراگمی می‌تواند بدون جراحی باشد.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
  ],
};
