import { ChapterData } from '@studyhub/shared-models';

export const chapter: ChapterData = {
  id: "ch09-infection",
  order: 8,
  code: "ch09",
  titleFa: "عفونت",
  titleEn: "Infection",
  summaryFa: "بانک سؤال تعاملی فصل عفونت نوزادی: عوامل خطر، ارزیابی، و اداره‌ی سپسیس نوزادی — بر پایه‌ی برنامه‌ی ACoRN.",
  readingMinutes: 55,
  sections: [
    {
      heading: "درباره‌ی این فصل",
      paragraphsHtml: ["<p>این فصل صرفاً شامل یک بانک سؤال تعاملی (چهارگزینه‌ای، کوتاه‌پاسخ، و صحیح/غلط) است که از کتاب «مراقبت بحرانی نوزاد در معرض خطر» (برنامه‌ی آموزشی ACoRN) اقتباس شده؛ بدون متن درسی جداگانه، مستقیماً به بانک سؤال زیر مراجعه کنید.</p>"],
    },
  ],
  quiz: [
    {
      id: "mcq1",
      type: 'mcq',
      question: "شایع‌ترین علت عفونت زودرس (Early-onset sepsis) در نوزادان کدام است؟",
      choices: ["عفونت داخل رحمی ناشی از microorganisms از مادر", "عفونت پس‌ازتولد", "عدم تغذیه", "عدم حرارت"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: عفونت داخل رحمی ناشی از microorganisms از مادر",
    },
    {
      id: "mcq2",
      type: 'mcq',
      question: "کدام عامل‌های بیماری‌زایی برای عفونت زودرس نوزادی رایج‌ترند؟",
      choices: ["Group B Streptococcus (GBS) و E. coli K1", "فقط Staphylococcus", "فقط Listeria", "فقط Candida"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: Group B Streptococcus (GBS) و E. coli K1",
    },
    {
      id: "mcq3",
      type: 'mcq',
      question: "عفونت دیررس (Late-onset sepsis) در نوزاد چه زمانی شروع می‌شود؟",
      choices: ["بعد از ۷۲ ساعت (۳ روز) تولد", "قبل از ۲۴ ساعت", "بعد از ۶ ماه", "بعد از یک سال"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: بعد از ۷۲ ساعت (۳ روز) تولد",
    },
    {
      id: "mcq4",
      type: 'mcq',
      question: "علامات بالینی عفونت نوزادی کدامند؟",
      choices: ["تب یا هیپوترمی، بی‌حالی، تغذیه ضعیف، تنفس سریع، و تاکیکاردی", "فقط گریه شدید", "فقط تنفس آرام", "بدون علامت"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: تب یا هیپوترمی، بی‌حالی، تغذیه ضعیف، تنفس سریع، و تاکیکاردی",
    },
    {
      id: "mcq5",
      type: 'mcq',
      question: "کدام نوازادان در معرض خطر بیشتری از عفونت قرار دارند؟",
      choices: ["نوزادان نارس، کم وزن، دارای روپچگی طولانی، و تخلیه دوران خون ناپایدار", "فقط نوزادان ترم", "فقط نوزادان سنگین", "بدون ریسک خاص"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: نوزادان نارس، کم وزن، دارای روپچگی طولانی، و تخلیه دوران خون ناپایدار",
    },
    {
      id: "mcq6",
      type: 'mcq',
      question: "بهترین روش تشخیص عفونت نوزادی کدام است؟",
      choices: ["جداسازی باکتری از خون (blood culture) و CSF", "فقط CBC", "فقط دمای بدن", "فقط رنگ پوست"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: جداسازی باکتری از خون (blood culture) و CSF",
    },
    {
      id: "mcq7",
      type: 'mcq',
      question: "کدام یافته در CBC نشان‌دهنده عفونت یا سپسیس در نوزاد است؟",
      choices: ["تغیر در تعداد WBC، تغیر در نسبت I:M، و تعداد پلاکت کم", "فقط هموگلوبین بالا", "فقط RBC کم", "بدون تغیر"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: تغیر در تعداد WBC، تغیر در نسبت I:M، و تعداد پلاکت کم",
    },
    {
      id: "mcq8",
      type: 'mcq',
      question: "درمان اولیه (Empiric therapy) برای شک به سپسیس زودرس کدام است؟",
      choices: ["Ampicillin (یا Penicillin) + Gentamicin", "فقط Penicillin", "فقط Gentamicin", "بدون درمان"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: Ampicillin (یا Penicillin) + Gentamicin",
    },
    {
      id: "mcq9",
      type: 'mcq',
      question: "دوز Ampicillin برای نوزاد (IV) چقدر است؟",
      choices: ["۵۰ mg/kg/dose هر ۶-۱۲ ساعت", "۱۰ mg/kg", "۲۰۰ mg/kg", "۵ mg/kg"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: ۵۰ mg/kg/dose هر ۶-۱۲ ساعت",
    },
    {
      id: "mcq10",
      type: 'mcq',
      question: "دوز Gentamicin برای نوزاد (IV) چقدر است؟",
      choices: ["۷/۵ mg/kg/dose هر ۲۴ ساعت (یا تقسیم‌شده)", "۱ mg/kg", "۵۰ mg/kg", "بدون دوز"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: ۷/۵ mg/kg/dose هر ۲۴ ساعت (یا تقسیم‌شده)",
    },
    {
      id: "mcq11",
      type: 'mcq',
      question: "کدام علایم نشان‌دهنده عفونت شدید یا مننژیت در نوزاد است؟",
      choices: ["تشنج، بدون پاسخ، فونتانل پیدار یا متورم", "فقط گریه", "فقط تنفس سریع", "بدون علامت خاص"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: تشنج، بدون پاسخ، فونتانل پیدار یا متورم",
    },
    {
      id: "mcq12",
      type: 'mcq',
      question: "کدام نمونه برای تشخیص مننژیت باید بگیرند؟",
      choices: ["مایع مغزی نخاعی (CSF) از lumbar puncture", "فقط خون", "فقط ادرار", "بدون نمونه"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: مایع مغزی نخاعی (CSF) از lumbar puncture",
    },
    {
      id: "mcq13",
      type: 'mcq',
      question: "کدام یافته‌های CSF نشان‌دهنده مننژیت باکتریایی است؟",
      choices: ["افزایش پروتئین، کاهش گلوکز، افزایش WBC (بیشتر neutrophils)", "کاهش پروتئین", "افزایش گلوکز", "هیچ تغیر"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: افزایش پروتئین، کاهش گلوکز، افزایش WBC (بیشتر neutrophils)",
    },
    {
      id: "mcq14",
      type: 'mcq',
      question: "مدت زمان درمان برای سپسیس نوزادی چقدر است؟",
      choices: ["۷-۱۰ روز", "۱-۲ روز", "۳۰ روز", "۶ ماه"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: ۷-۱۰ روز",
    },
    {
      id: "mcq15",
      type: 'mcq',
      question: "درمان مننژیت نوزادی (اگر تأیید شود) کدام است؟",
      choices: ["Cefotaxime یا Ceftriaxone + Ampicillin ± Gentamicin", "فقط Penicillin", "فقط Gentamicin", "بدون درمان خاص"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: Cefotaxime یا Ceftriaxone + Ampicillin ± Gentamicin",
    },
    {
      id: "mcq16",
      type: 'mcq',
      question: "دوز Cefotaxime برای نوزاد با مننژیت چقدر است؟",
      choices: ["۵۰ mg/kg/dose هر ۶-۸ ساعت", "۱۰ mg/kg", "۱۰۰ mg/kg", "۲۰۰ mg/kg"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: ۵۰ mg/kg/dose هر ۶-۸ ساعت",
    },
    {
      id: "mcq17",
      type: 'mcq',
      question: "آیا نوزادان دارای عفونت احتمالی باید تجویز دوزهای Acyclovir شوند؟",
      choices: ["بلی، برای پوشش احتمالی Herpes simplex؛ Acyclovir ۲۰ mg/kg/dose هر ۸ ساعت", "خیر، هیچ نیاز نیست", "تنها اگر تب باشند", "بدون توصیه"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: بلی، برای پوشش احتمالی Herpes simplex؛ Acyclovir ۲۰ mg/kg/dose هر ۸ ساعت",
    },
    {
      id: "mcq18",
      type: 'mcq',
      question: "علامات نشان‌دهنده عفونت ویروسی (Herpes neonatal) کدامند؟",
      choices: ["بثرات جلدی، چشم‌بند، یا علائم مننژیتی بعد از ۳-۵ روز", "فقط تب", "فقط بدون گریه", "بدون علامت محسوس"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: بثرات جلدی، چشم‌بند، یا علائم مننژیتی بعد از ۳-۵ روز",
    },
    {
      id: "mcq19",
      type: 'mcq',
      question: "کدام عامل ریسک برای عفونت Listeria monocytogenes در نوزادان است؟",
      choices: ["عفونت مادر بدون علامت یا کم‌علامت", "فقط نوزادان نارس", "فقط دیابتی‌های مادر", "بدون ریسک خاص"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: عفونت مادر بدون علامت یا کم‌علامت",
    },
    {
      id: "mcq20",
      type: 'mcq',
      question: "درمان عفونت Listeria کدام است؟",
      choices: ["Ampicillin یا Penicillin (Cephalosporins موثر نیستند)", "فقط Cephalosporin", "فقط Gentamicin", "بدون نیاز درمان"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: Ampicillin یا Penicillin (Cephalosporins موثر نیستند)",
    },
    {
      id: "mcq21",
      type: 'mcq',
      question: "Procalcitonin چه کاربردی در تشخیص عفونت دارد؟",
      choices: ["نشانگر بهتری برای عفونت باکتریایی نسبت به CRP", "بدون کاربرد", "فقط برای ویروسی", "برای تشخیص تب"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: نشانگر بهتری برای عفونت باکتریایی نسبت به CRP",
    },
    {
      id: "mcq22",
      type: 'mcq',
      question: "C-Reactive Protein (CRP) در عفونت نوزادی چگونه است؟",
      choices: ["عادتاً افزایش یافته در عفونت باکتریایی", "همیشه نرمال", "کاهش یافته", "بدون تأثیر"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: عادتاً افزایش یافته در عفونت باکتریایی",
    },
    {
      id: "mcq23",
      type: 'mcq',
      question: "کدام عامل بیماری‌زایی برای عفونت دیررس رایج است؟",
      choices: ["Coagulase-negative Staphylococcus (خصوصاً در خطوط وریدی)", "فقط GBS", "فقط E. coli", "فقط Listeria"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: Coagulase-negative Staphylococcus (خصوصاً در خطوط وریدی)",
    },
    {
      id: "mcq24",
      type: 'mcq',
      question: "زمان شروع درمان در شک به عفونت نوزادی کدام است؟",
      choices: ["درست بعد از فرضیه بالینی و جمع‌آوری خون برای culture", "تنها بعد از نتایج culture", "تنها اگر ثابت شود", "بدون عجله"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: درست بعد از فرضیه بالینی و جمع‌آوری خون برای culture",
    },
    {
      id: "mcq25",
      type: 'mcq',
      question: "کدام نشانه نشان‌دهنده بهبود عفونت در نوزاد است؟",
      choices: ["بهبود سطح آگاهی، علائم حیاتی پایدار، و نتایج آزمایش‌های نرمال شده", "ادامه تب", "افزایش WBC", "بدون بهبود"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: بهبود سطح آگاهی، علائم حیاتی پایدار، و نتایج آزمایش‌های نرمال شده",
    },
    {
      id: "mcq26",
      type: 'mcq',
      question: "آیا تمام نوزادان نیازمند lumbar puncture برای تشخیص هستند؟",
      choices: ["خیر، اما توصیه می‌شود در موارد مننژیت مشکوک یا عفونت شدید", "بلی، تمام موارد", "هرگز نباید انجام شود", "فقط برای تب"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: خیر، اما توصیه می‌شود در موارد مننژیت مشکوک یا عفونت شدید",
    },
    {
      id: "mcq27",
      type: 'mcq',
      question: "مدت زمان درمان مننژیت نوزادی چقدر است؟",
      choices: ["۱۴-۲۱ روز", "۳-۵ روز", "۳۰ روز", "۶ ماه"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: ۱۴-۲۱ روز",
    },
    {
      id: "mcq28",
      type: 'mcq',
      question: "کدام یافته اشاره‌کننده به عفونت ویروسی به جای باکتریایی است؟",
      choices: ["CSF با lymphocytosis و گلوکز نرمال یا کمی کاهش‌یافته", "عصیات gram-positive", "باکتری در culture", "بدون تفاوت"],
      correctIndex: 0,
      explanation: "پاسخ صحیح: CSF با lymphocytosis و گلوکز نرمال یا کمی کاهش‌یافته",
    },
    {
      id: "short1",
      type: 'short',
      prompt: "عفونت زودرس نوزادی چیست و چه عوامل ریسک آن هستند؟",
      answer: "سپسیس شروع‌شده در ۷۲ ساعت اول (معمولاً ۲۴ ساعت)؛ ریسک: روپچگی طولانی (>۱۸ ساعت)، عفونت مادر یا تب در حین زایمان، انجام ناپایدار.",
    },
    {
      id: "short2",
      type: 'short',
      prompt: "عامل‌های رایج سپسیس زودرس نوزادی کدامند؟",
      answer: "Group B Streptococcus (GBS) و E. coli K1 شایع‌ترند؛ Listeria monocytogenes نیز ممکن است.",
    },
    {
      id: "short3",
      type: 'short',
      prompt: "علامات بالینی سپسیس نوزادی را بیان کنید.",
      answer: "تب (>۳۸/۵°) یا هیپوترمی (<۳۶/۵°)، بی‌حالی، تغذیه ضعیف، تنفس سریع (RDS-like)، تاکیکاردی، و بدون پاسخ.",
    },
    {
      id: "short4",
      type: 'short',
      prompt: "بهترین روش تشخیص عفونت نوزادی کدام است؟",
      answer: "جداسازی باکتری یا ویروس از خون، CSF، و ادرار (سریالی)؛ CBC با تفاوت، CRP یا Procalcitonin.",
    },
    {
      id: "short5",
      type: 'short',
      prompt: "درمان اولیه برای شک به سپسیس زودرس کدام است؟",
      answer: "Ampicillin (۵۰ mg/kg/dose هر ۱۲ ساعت) + Gentamicin (۷/۵ mg/kg/dose) شروع درست بعد از فرضیه بالینی.",
    },
    {
      id: "short6",
      type: 'short',
      prompt: "تفاوت بین عفونت زودرس و دیررس چیست؟",
      answer: "زودرس: <۷۲ ساعت، معمولاً ناشی از مادر (transplacental یا ascending)؛ دیررس: >۷۲ ساعت، منشأ محیطی (hospital-acquired یا community).",
    },
    {
      id: "short7",
      type: 'short',
      prompt: "علامات مننژیت نوزادی کدامند؟",
      answer: "تشنج، بدون پاسخ، فونتانل متورم، برطرفی عصبی، و یافته‌های CSF غیرنرمال.",
    },
    {
      id: "short8",
      type: 'short',
      prompt: "کدام نمونه‌ها برای تشخیص عفونت جمع‌آوری شوند؟",
      answer: "خون برای culture، CSF از lumbar puncture (اگر مننژیت مشکوک)، ادرار (سریالی)، و گلاب یا ترشحات دهان اگر شدید.",
    },
    {
      id: "short9",
      type: 'short',
      prompt: "یافته‌های CSF در مننژیت باکتریایی نوزادی چیست؟",
      answer: "پروتئین ۱۰۰-۲۰۰ (یا بیشتر)، گلوکز < ۳۰ mg/dL یا نسبت گلوکز CSF/خون <۰/۴، WBC > ۱۰۰ (بیشتر neutrophils).",
    },
    {
      id: "short10",
      type: 'short',
      prompt: "مدت درمان سپسیس و مننژیت نوزادی چقدر است؟",
      answer: "سپسیس: ۷-۱۰ روز؛ مننژیت: ۱۴-۲۱ روز، بسته به عامل و پاسخ بالینی.",
    },
    {
      id: "short11",
      type: 'short',
      prompt: "درمان مننژیت اگر تأیید شود کدام است؟",
      answer: "Cefotaxime (۵۰ mg/kg/dose هر ۶-۸ ساعت) یا Ceftriaxone + Ampicillin ± Gentamicin برای پوشش Listeria.",
    },
    {
      id: "short12",
      type: 'short',
      prompt: "چرا نباید تنها Cephalosporin برای Listeria استفاده کنند؟",
      answer: "Listeria monocytogenes به Cephalosporins مقاوم است؛ باید Ampicillin یا Penicillin استفاده شود.",
    },
    {
      id: "short13",
      type: 'short',
      prompt: "درمان عفونت Herpes simplex نوزادی کدام است؟",
      answer: "Acyclovir ۲۰ mg/kg/dose هر ۸ ساعت (IV) برای ۱۰-۱۴ روز؛ درمان باید زودتر شروع شود اگر مشکوک باشد.",
    },
    {
      id: "short14",
      type: 'short',
      prompt: "علامات عفونت Herpes نوزادی کدامند؟",
      answer: "بثرات جلدی (vesicular rash)، چشم‌بند (keratoconjunctivitis)، یا علائم مننژیتی/ضد‌التهابی بعد از ۳-۵ روز.",
    },
    {
      id: "short15",
      type: 'short',
      prompt: "کدام نشانگر بهتری برای عفونت باکتریایی است: CRP یا Procalcitonin؟",
      answer: "Procalcitonin بهتر است؛ بیشتر ویژه برای عفونت باکتریایی، کمتر متأثر از بیماری‌های غیرعفونی.",
    },
    {
      id: "short16",
      type: 'short',
      prompt: "عامل ریسک برای عفونت Candida در نوزادان چیست؟",
      answer: "استفاده طولانی از antibiotics، venous lines (خصوصاً central)، و nutrition محیطی مطلوب.",
    },
    {
      id: "short17",
      type: 'short',
      prompt: "درمان عفونت Candida نوزادی کدام است؟",
      answer: "Fluconazole (۶ mg/kg/dose هر ۲۴ ساعت) یا Amphotericin B، بسته به شدت و توطئه عضو.",
    },
    {
      id: "short18",
      type: 'short',
      prompt: "چه زمانی باید Acyclovir برای عفونت مشکوک ویروسی اضافه کنند؟",
      answer: "زمانی که ریسک Herpes simplex وجود داشته باشد (مثلاً تاریخ Herpes مادر، علائم atypical یا CSF lymphocytosis).",
    },
    {
      id: "short19",
      type: 'short',
      prompt: "نقش GBS prevention (مادری screening/prophylaxis) چیست؟",
      answer: "تشخیص و درمان Intrapartum antibiotic prophylaxis برای مادران GBS-positive جهت کاهش خطر عفونت نوزادی.",
    },
    {
      id: "short20",
      type: 'short',
      prompt: "علامات بهبود عفونت در نوزاد کدامند؟",
      answer: "بهبود سطح آگاهی، کاهش مصرف صورتین، علائم حیاتی پایدار و نرمال، و نرمال‌شدن CBC و CRP.",
    },
    {
      id: "tf1",
      type: 'truefalse',
      statement: "عفونت زودرس نوزادی همیشه با تب همراه است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf2",
      type: 'truefalse',
      statement: "Group B Streptococcus شایع‌ترین عامل عفونت زودرس است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf3",
      type: 'truefalse',
      statement: "روپچگی طولانی (>۱۸ ساعت) عامل ریسک برای عفونت است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf4",
      type: 'truefalse',
      statement: "درمان عفونت باید تنها بعد از نتایج culture شروع شود.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf5",
      type: 'truefalse',
      statement: "Ampicillin مؤثر برای Listeria monocytogenes است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf6",
      type: 'truefalse',
      statement: "Cephalosporin برای Listeria موثر است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf7",
      type: 'truefalse',
      statement: "تشنج نشانه‌ای از مننژیت نوزادی است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf8",
      type: 'truefalse',
      statement: "گلوکز CSF در مننژیت باکتریایی معمولاً افزایش می‌یابد.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf9",
      type: 'truefalse',
      statement: "WBC در CSF در عفونت باکتریایی افزایش می‌یابد.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf10",
      type: 'truefalse',
      statement: "درمان سپسیس برای ۷-۱۰ روز است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf11",
      type: 'truefalse',
      statement: "درمان مننژیت برای ۱۴-۲۱ روز است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf12",
      type: 'truefalse',
      statement: "Acyclovir برای Herpes simplex نوزادی موثر است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf13",
      type: 'truefalse',
      statement: "عفونت Herpes نوزادی همیشه با بثرات جلدی شروع می‌شود.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf14",
      type: 'truefalse',
      statement: "Procalcitonin بهتری برای عفونت نسبت به CRP است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf15",
      type: 'truefalse',
      statement: "Candida عفونت معمولاً در نوزادان ترم رخ می‌دهد.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf16",
      type: 'truefalse',
      statement: "استفاده Central venous line ریسک عفونت را افزایش می‌دهد.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf17",
      type: 'truefalse',
      statement: "عفونت دیررس معمولاً بعد از ۷۲ ساعت شروع می‌شود.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf18",
      type: 'truefalse',
      statement: "Coagulase-negative Staphylococcus معمول‌ترین عامل عفونت دیررس است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf19",
      type: 'truefalse',
      statement: "تمام نوزادان دارای شک به عفونت نیاز به lumbar puncture دارند.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf20",
      type: 'truefalse',
      statement: "تب در نوزاد همیشه علامت عفونت است.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf21",
      type: 'truefalse',
      statement: "بی‌حالی علامت بالینی مهم سپسیس است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf22",
      type: 'truefalse',
      statement: "تغذیه ضعیف می‌تواند علامت سپسیس باشد.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf23",
      type: 'truefalse',
      statement: "Gentamicin مؤثر برای E. coli است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf24",
      type: 'truefalse',
      statement: "Ampicillin مؤثر برای GBS است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf25",
      type: 'truefalse',
      statement: "عفونت مادر باعث عفونت نوزاد نمی‌شود.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf26",
      type: 'truefalse',
      statement: "پروتئین CSF در مننژیت باکتریایی افزایش می‌یابد.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf27",
      type: 'truefalse',
      statement: "عفونت ویروسی همیشه به antibiotics نیاز دارد.",
      isTrue: false,
      explanation: "این گزاره طبق منبع نادرست است.",
    },
    {
      id: "tf28",
      type: 'truefalse',
      statement: "Listeria از طریق رژیم غذایی مادر منتقل می‌شود.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf29",
      type: 'truefalse',
      statement: "درمان عفونت Candida Fluconazole است.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
    {
      id: "tf30",
      type: 'truefalse',
      statement: "تشنج می‌تواند نتیجه‌ای از مننژیت باکتریایی باشد.",
      isTrue: true,
      explanation: "این گزاره طبق منبع درست است.",
    },
  ],
};
