export interface GlossaryTerm {
  fa: string;
  en: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { fa: 'سکون رحم', en: 'Uterine quiescence' },
  { fa: 'رسیدگی سرویکس', en: 'Cervical ripening' },
  { fa: 'افاسمان', en: 'Cervical effacement' },
  { fa: 'دیلاتاسیون', en: 'Dilation' },
  { fa: 'نزول جنین', en: 'Fetal descent' },
  { fa: 'کیسه‌ی پیشین', en: 'Forebag' },
  { fa: 'انقباضات براکستون هیکس', en: 'Braxton-Hicks contractions' },
  { fa: 'سبک‌شدگی', en: 'Lightening' },
  { fa: 'علامت هگار', en: 'Hegar sign' },
  { fa: 'هیالورونان', en: 'Hyaluronan' },
  { fa: 'ریلاکسین', en: 'Relaxin' },
  { fa: 'اتصال شکاف‌دار', en: 'Gap junction' },
  { fa: 'کانکسین ۴۳', en: 'Connexin-43' },
  { fa: 'پروستاگلاندین دهیدروژناز', en: 'PGDH' },
  { fa: 'رفلکس فرگوسن', en: 'Ferguson reflex' },
  { fa: 'حلقه‌ی باندل', en: 'Bandl\'s ring' },
  { fa: 'مکانیسم شولتز', en: 'Schultze mechanism' },
  { fa: 'مکانیسم دانکن', en: 'Duncan mechanism' },
  { fa: 'هماتوم رتروپلاسنتال', en: 'Retroplacental hematoma' },
  { fa: 'نفاس', en: 'Puerperium' },
  { fa: 'آنتاگونیست گیرنده پروژسترون', en: 'Mifepristone (RU-486)' },
  { fa: 'قرار (طولی/عرضی)', en: 'Fetal lie' },
  { fa: 'حالت جنین', en: 'Fetal attitude / habitus' },
  { fa: 'وضعیت جنین', en: 'Fetal position' },
  { fa: 'مانورهای لئوپولد', en: 'Leopold maneuvers' },
  { fa: 'حرکات اصلی لیبر', en: 'Cardinal movements of labor' },
  { fa: 'آنگاژمان', en: 'Engagement' },
  { fa: 'آسنکلیتیسم', en: 'Asynclitism' },
  { fa: 'عدم تناسب سری-لگنی', en: 'Cephalopelvic disproportion (CPD)' },
  { fa: 'دیستوشی', en: 'Dystocia' },
  { fa: 'کاپوت سوکسدانئوم', en: 'Caput succedaneum' },
  { fa: 'مولدینگ', en: 'Molding' },
  { fa: 'تست نیترازین / فرنینگ', en: 'Nitrazine test / Ferning' },
  { fa: 'واحد مونته‌ویدئو', en: 'Montevideo unit' },
  { fa: 'لیبر تسریع‌شده', en: 'Precipitous labor' },
  { fa: 'نمایش صورت (منتوم)', en: 'Face presentation (mentum)' },
  { fa: 'قرار عرضی فراموش‌شده', en: 'Neglected transverse lie' },
  { fa: 'پرولاپس بندناف', en: 'Umbilical cord prolapse' },
  { fa: 'کنژوگه دیاگونال/آبستتریک', en: 'Diagonal / obstetric conjugate' },
  { fa: 'اختلال هیپوتونیک/هیپرتونیک رحم', en: 'Hypotonic / hypertonic uterine dysfunction' },
  { fa: 'تغییرپذیری ضربه‌به‌ضربه', en: 'Beat-to-beat variability' },
  { fa: 'تسریع', en: 'Acceleration' },
  { fa: 'افت زودرس/دیررس/متغیر', en: 'Early / late / variable deceleration' },
  { fa: 'الگوی سینوزوئیدی', en: 'Sinusoidal pattern' },
  { fa: 'تاکی‌سیستول', en: 'Tachysystole' },
  { fa: 'آمنیوانفوزیون', en: 'Amnioinfusion' },
  { fa: 'تحریک ویبروآکوستیک', en: 'Vibroacoustic stimulation' },
  { fa: 'پالس اکسی‌متری جنین', en: 'Fetal pulse oximetry' },
  { fa: 'دیستوشی شانه', en: 'Shoulder dystocia' },
  { fa: 'نشانه‌ی لاک‌پشت', en: 'Turtle sign' },
  { fa: 'مانور مک‌رابرتز', en: 'McRoberts maneuver' },
  { fa: 'مانور وودز کورک‌اسکرو', en: 'Woods corkscrew maneuver' },
  { fa: 'مانور زاوانلی', en: 'Zavanelli maneuver' },
  { fa: 'ختنه‌ی زنان', en: 'Female genital mutilation (FGM)' },
  { fa: 'آسیب اسفنکتر مقعد زایمانی', en: 'OASIS' },
  { fa: 'اپیزیاتومی خط وسط/مدیولترال', en: 'Midline / mediolateral episiotomy' },
  { fa: 'کراونینگ', en: 'Crowning' },
  { fa: 'وارونگی رحم', en: 'Uterine inversion' },
  { fa: 'بریچ فرانک/کامل/فوتلینگ', en: 'Frank / complete / footling breech' },
  { fa: 'جنین خیره به آسمان', en: 'Stargazing fetus' },
  { fa: 'جنین پرنده', en: 'Flying fetus' },
  { fa: 'مانور مورسیو', en: 'Mauriceau maneuver' },
  { fa: 'مانور تعدیل‌شده‌ی پراگ', en: 'Modified Prague maneuver' },
  { fa: 'فورسپس پایپر', en: 'Piper forceps' },
  { fa: 'انسزیون دورسن', en: 'Dührssen incisions' },
  { fa: 'چرخش سفالیک خارجی', en: 'External cephalic version (ECV)' },
  { fa: 'چرخش پودالیک داخلی', en: 'Internal podalic version' },
  { fa: 'پولیپ جفتی', en: 'Placental polyp' },
  { fa: 'خونریزی تأخیری پس از زایمان', en: 'Delayed postpartum hemorrhage' },
  { fa: 'کارنکول میرتیفورم', en: 'Myrtiform caruncle' },
  { fa: 'رفلکس خروج شیر', en: 'Letting-down reflex' },
  { fa: 'کلستروم (آغوز)', en: 'Colostrum' },
  { fa: 'اندوهگینی پس از زایمان', en: 'Postpartum blues' },
  { fa: 'نوروپاتی عصب جلدی رانی جانبی', en: 'Lateral femoral cutaneous neuropathy' },
  { fa: 'جداشدگی سمفیزیوپوبیس', en: 'Symphyseal separation' },
  { fa: 'حالت جنین (اتیتود)', en: 'Fetal attitude' },
  { fa: 'آنگاژمان', en: 'Engagement' },
  { fa: 'انحراف نائجله / لیتزمن', en: 'Naegele\'s / Litzmann\'s obliquity' },
  { fa: 'کاپوت سوکسدانئوم', en: 'Caput succedaneum' },
  { fa: 'مانور ریتگن', en: 'Ritgen maneuver' },
  { fa: 'کراونینگ', en: 'Crowning' },
  { fa: 'اداره‌ی فعال مرحله سوم', en: 'Active management of third stage' },
  { fa: 'سنتوسینون / مترژین', en: 'Syntocinon / Methergine' },
  { fa: 'طبقه‌بندی سه‌گروهی NICHD', en: 'NICHD 3-tier category system' },
  { fa: 'تحلیل قطعه ST جنین', en: 'Fetal ST-segment analysis (STAN)' },
  { fa: 'واحد مونته‌ویدئو', en: 'Montevideo unit (MVU)' },
  { fa: 'سندرم آسپیراسیون مکونیوم', en: 'Meconium aspiration syndrome' },
  { fa: 'سلطه‌ی فوندال', en: 'Fundal dominance' },
  { fa: 'شاخص مایع آمنیوتیک', en: 'Amniotic fluid index (AFI)' },
  { fa: 'هیدرآمنیوس / الیگوهیدرآمنیوس', en: 'Hydramnios / Oligohydramnios' },
  { fa: 'سندرم پاتر', en: 'Potter sequence' },
  { fa: 'استفراغ شدید حاملگی', en: 'Hyperemesis gravidarum' },
  { fa: 'آشالازی', en: 'Achalasia' },
  { fa: 'بیماری التهابی روده', en: 'Inflammatory bowel disease (IBD)' },
  { fa: 'سندرم اُگیلوی', en: 'Ogilvie syndrome' },
  { fa: 'آپاندیسیت', en: 'Appendicitis' },
  { fa: 'قانون نگل', en: 'Naegele\'s rule' },
  { fa: 'علامت چادویک', en: 'Chadwick\'s sign' },
  { fa: 'نقص لوله عصبی', en: 'Neural tube defect (NTD)' },
  { fa: 'پیکا', en: 'Pica' },
  { fa: 'پتیالیسم', en: 'Ptyalism' },
  { fa: 'ذخیره‌سازی خون بندناف', en: 'Cord blood banking' },
  { fa: 'ایمونوگلوبولین آنتی-D (روگام)', en: 'Anti-D immunoglobulin (RhoGAM)' },
];
